# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rpc.raman_pb2 as raman__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in raman_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RamanStub(object):
    """The Raman service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeviceList = channel.unary_unary(
                '/raman.Raman/GetDeviceList',
                request_serializer=raman__pb2.Empty.SerializeToString,
                response_deserializer=raman__pb2.DeviceList.FromString,
                _registered_method=True)
        self.DeviceCheck = channel.unary_unary(
                '/raman.Raman/DeviceCheck',
                request_serializer=raman__pb2.Empty.SerializeToString,
                response_deserializer=raman__pb2.DeviceStatus.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/raman.Raman/Connect',
                request_serializer=raman__pb2.ConnectRequest.SerializeToString,
                response_deserializer=raman__pb2.DeviceStatus.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/raman.Raman/Disconnect',
                request_serializer=raman__pb2.Empty.SerializeToString,
                response_deserializer=raman__pb2.DeviceStatus.FromString,
                _registered_method=True)
        self.ReadCCD = channel.unary_stream(
                '/raman.Raman/ReadCCD',
                request_serializer=raman__pb2.Empty.SerializeToString,
                response_deserializer=raman__pb2.CCD.FromString,
                _registered_method=True)
        self.SetMeasureConf = channel.unary_unary(
                '/raman.Raman/SetMeasureConf',
                request_serializer=raman__pb2.MeasureConfRequest.SerializeToString,
                response_deserializer=raman__pb2.DeviceStatus.FromString,
                _registered_method=True)


class RamanServicer(object):
    """The Raman service definition.
    """

    def GetDeviceList(self, request, context):
        """Checks the device status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCCD(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMeasureConf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RamanServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeviceList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceList,
                    request_deserializer=raman__pb2.Empty.FromString,
                    response_serializer=raman__pb2.DeviceList.SerializeToString,
            ),
            'DeviceCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceCheck,
                    request_deserializer=raman__pb2.Empty.FromString,
                    response_serializer=raman__pb2.DeviceStatus.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=raman__pb2.ConnectRequest.FromString,
                    response_serializer=raman__pb2.DeviceStatus.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=raman__pb2.Empty.FromString,
                    response_serializer=raman__pb2.DeviceStatus.SerializeToString,
            ),
            'ReadCCD': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadCCD,
                    request_deserializer=raman__pb2.Empty.FromString,
                    response_serializer=raman__pb2.CCD.SerializeToString,
            ),
            'SetMeasureConf': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMeasureConf,
                    request_deserializer=raman__pb2.MeasureConfRequest.FromString,
                    response_serializer=raman__pb2.DeviceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raman.Raman', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raman.Raman', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Raman(object):
    """The Raman service definition.
    """

    @staticmethod
    def GetDeviceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raman.Raman/GetDeviceList',
            raman__pb2.Empty.SerializeToString,
            raman__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raman.Raman/DeviceCheck',
            raman__pb2.Empty.SerializeToString,
            raman__pb2.DeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raman.Raman/Connect',
            raman__pb2.ConnectRequest.SerializeToString,
            raman__pb2.DeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raman.Raman/Disconnect',
            raman__pb2.Empty.SerializeToString,
            raman__pb2.DeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadCCD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/raman.Raman/ReadCCD',
            raman__pb2.Empty.SerializeToString,
            raman__pb2.CCD.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMeasureConf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raman.Raman/SetMeasureConf',
            raman__pb2.MeasureConfRequest.SerializeToString,
            raman__pb2.DeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
