FROM mcr.microsoft.com/dotnet/sdk:9.0-noble

ARG BUILD_VERSION
ENV BUILD_VERSION=$BUILD_VERSION

# Ubuntu already have `ubuntu` user
ARG USER
ARG GID
ARG UID
ARG WORKDIR
# Create the user
# RUN groupadd --gid $GID $USER \
#     && useradd --uid $UID --gid $GID -m $USER
    
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
RUN apt update \
    && apt-get install -y sudo \
    && echo $USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# Common tools
RUN apt install -y --no-install-recommends ssh vim iputils-ping telnet wget

RUN apt clean
RUN rm -rf /var/lib/apt/lists/*


# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USER
WORKDIR ${WORKDIR}